[cr148] //third_party/mock removed from gsutil third_party code
//third_party/mock was removed from the gsutil third_party code. We were
previously touching the Changelog file in this directory because it was needed
for our test suites to run properly on Android (see
https://github.com/brave/brave-browser/issues/31641). However, we can no longer
do that so removed that code.

Chromium changes:
https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/ac70fe6a2cd8d142ff08e4692fa3230fb954a211

commit ac70fe6a2cd8d142ff08e4692fa3230fb954a211
Author: Andrew Grieve <agrieve@chromium.org>
Date:   Thu Mar 12 14:36:11 2026 -0400

    Roll //third_party/gsutil 5.29 -> 5.36

    And also set "Shipped: No" in the README.chromium

    Required to support python3. Currently, I'm seeing:

    >>> from devil.android import device_utils
    >>> d = device_utils.DeviceUtils.HealthyDevices()
    <snip>
      File "/usr/local/google/code/clankium-rebaser/src/third_party/catapult/third_party/gsutil/third_party/apitools/apitools/base/protorpclite/messages.py", line 319, in __init__
        raise EnumDefinitionError(
        ...<2 lines>...
            (attribute, value))
    apitools.base.protorpclite.messages.EnumDefinitionError: May only use integers in Enum definitions.  Found: __static_attributes__ = ()

    Change-Id: Ieb949db930984a1a84061b3a0a2159b12e5c0e30
    Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/7658464
    Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
    Auto-Submit: Andrew Grieve <agrieve@chromium.org>
    Reviewed-by: Haiyang Pan <hypan@google.com>
    Reviewed-by: Brian Sheedy <bsheedy@chromium.org>