[cr148][Android] WIP SidePanelUI::Toggle default empty implementation
Marked as WIP because I don't know how does it affect Android.

The commit is intended to fix this build error:

../../chrome/browser/ui/side_panel/internal/android/side_panel_coordinator_android.cc:22:11: error: allocating an object of abstract class type 'SidePanelCoordinatorAndroid'
   22 |       new SidePanelCoordinatorAndroid(env, caller));
      |           ^
../../chrome/browser/ui/side_panel/side_panel_ui.h:62:16: note: unimplemented pure virtual method 'Toggle' in 'SidePanelCoordinatorAndroid'
   62 |   virtual void Toggle(SidePanelEntryKey key,
      |                ^
../../brave/chromium_src/chrome/browser/ui/side_panel/side_panel_ui.h:10:3: note: expanded from macro 'Toggle'
   10 |   Toggle() = 0; \
      |   ^
1 error generated.